[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]

[ai-internal]

exten => 700,1,NoOp(Sending call to Python ARI)
 same => n,Stasis(ai-agent)
 same => n,Hangup()

exten => 600,1,Answer()
 same => n,Echo()
 same => n,Hangup()

exten => 1000,1,Answer()
 same => n,Playback(demo-congrats)
 same => n,Hangup()
